### ISSUE TITLE
Not respond 

### ISSUE THREAD

**Issue by mengheangrat** [Alwinator/react-native-http-bridge-refurbished#18] opened 2023-07-01 08:09 UTC
server.get('/', async (req, res) => {
      return { message: 'OK' }
    })

server keep requesting. `(52) Empty reply from server`

**Comment by Alwinator** [comment] 2023-08-21 08:43
@mengheangrat Can you maybe provide more context on how to reproduce the issue? Maybe an example project. On which platform are you, and in which versions does the issue appear?

**Comment by abdelhameedhamdy** [comment] 2023-08-29 10:35
Same issue :
curl: (52) Empty reply from server

 "react-native": "0.72.4",
MacBook Air M1

**Comment by abdelhameedhamdy** [comment] 2023-08-29 10:55
repo to reproduce this issue : 
https://github.com/abdelhameedhamdy/rn-http-server

**Comment by Alwinator** [comment] 2023-08-30 17:15
Since this bug is the same as #21. I will close this thread. Please check #21 for news.

**Closed by Alwinator** 2023-08-30 17:15 UTC
Labels: bug
